### PR TITLE
WIP - Add toggle area functionality 

### PR DESCRIPTION
**Pull request by timarney**
@dsamojlenko 

This is a first attempt for adding a generic show hide functionally

See:

https://cds-node-starter-pr-42.herokuapp.com/personal
```
Would you like to receive notifications? 
()
()
```

Which should toggle
```
Notify by
[]
[]
```

@sastels is looking to have that functionality here
https://github.com/cds-snc/simplify-privacy-statements-V2

See my notes here in this file https://github.com/cds-snc/node-starter-app/pull/42/files#diff-b88a18411aa47e705f22c244ccee5d88

- i.e. passing data attributes etc... to individual inputs being looped over.

### CODE REVIEW

**Comment by sastels** [comment]
❤️

**Comment by timarney** [comment]
@dsamojlenko any thoughts?

**Comment by smcmurtry** [comment]
@timarney is it possible to make the "notify by" question default hidden?

**Comment by timarney** [comment]
@smcmurtry  you should be able to add a class 

```
.visually-hidden
```

To handle that.

**Comment by timarney** [comment]
Going to work with @dsamojlenko to figure out the format a bit more 





Which ties back to 
https://github.com/cds-snc/node-starter-app/issues/48

and 

https://github.com/cds-snc/node-starter-app/pull/57

We need a way to send data to individual elements for things like radios, checkboxes and selects

```
{{ radioButtons('group_name_for_input', { 'input_1': {classes: "yyy" , id: '"yyy", data-attr: "yyy"},'input_2':{}}) }}
```

Where the object would contain the properties you want to apply to the individual element.

This will end up being a breaking change but simplify / make things more robust moving forward.

**Comment by timarney** [comment]
Closing - will create a fresh PR once https://github.com/cds-snc/node-starter-app/pull/57 or sorted out.

**Comment by timarney** [comment]
Note the code is in use here https://github.com/cds-snc/simplify-privacy-statements-V2

**Pull request closed without merging**
