### PR TITLE
Simplify text input attributes/interface

### PR DESCRIPTION
**Pull request by dsamojlenko**
related to #48

### CODE REVIEW

**Comment by dsamojlenko** [comment]
@timarney yeah, I think this is good ... removed the `value` attribute, using `data[name]` ... cleaned up a few things.

This doesn't address what we'd talked about with the radio/checkboxes ... just text inputs.

**Comment by timarney** [comment]
>This doesn't address what we'd talked about with the radio/checkboxes ... just text inputs.

This should help with that issue.

https://github.com/cds-snc/node-starter-app/pull/69

**Comment by timarney** [comment]
Note: will need to add this textArea as well.  Not sure if you want to add that to this PR.

**Comment by timarney** [comment]
Also let's track these updates here

https://github.com/cds-snc/node-starter-app/pull/70

**Comment by timarney** [comment]
If you pull down the latest - you can make a note of the updates in the changelog file.

Outside of that + bumping the version should be good on this 👍

**Pull request merged**
