### PR TITLE
feature/Add windows support

### PR DESCRIPTION
**Pull request by sboisvert**
Add info on how to run on windows.

We could also do npm install --save-optional win-node-env if people think it's better to solve it for this package

### CODE REVIEW

**Comment by CalvinRodo** [comment]
In my experience with trying to sell something to devs in Government you need to make it as easy as possible, also the vast majority of government developers do their work on windows machines. 

Ideally this should be able to be brought up in windows without any extra work.

**Comment by timarney** [comment]
@sboisvert @CalvinRodo 

Just testing this on a fresh windows box.

Will document further as we go.

Initial issue without that package

```
NODE_ENV=development nodemon ./bin/www
```

NODE_ENV is not recognized as an internal or external command, operable program or batch file.

**Comment by timarney** [comment]
Looking at this further we'll use https://www.npmjs.com/package/cross-env which will work in "all the cases" without the global install. 

Outside of that issue "it just works".

Once we get that setup it will truly just work.

**Comment by sboisvert** [comment]
@timarney Sorry! I didn't see your comments before pushing my changes. I agree that cross env is probably best. Do you want me to kill this PR or change it?

**Comment by timarney** [comment]
Closing this in favour of:
https://github.com/cds-snc/node-starter-app/pull/100

**Pull request closed without merging**
