### PR TITLE
Move scss files out of public

### PR DESCRIPTION
**Pull request by dsamojlenko**
Moves scss files out of the public directory into a resources folder.

Open to alternate suggestions for where they should go, but pretty sure they don't belong in public.

### CODE REVIEW

**Comment by jneen** [comment]
`assets/` is a common choice in projects I've been in before.

**Comment by timarney** [comment]
@pcraig3 @katedee any thoughts on directory name to hold .sass files outside of the public dir

- resources
- assets
- don't care

**Comment by timarney** [comment]
@dsamojlenko we can either merge this as is and change later if people have opinions or if you want to call it assets let me know.

**Comment by dsamojlenko** [comment]
I think assets is good. I'll make the change.

**Comment by timarney** [comment]
Feel free to merge.

**Pull request merged**
